- src/canvas-2d-shape-renderer.js
- src/canvas-2d-text-renderer.js
Fixes to Text renderer js and shape renderer js
> Fixes #15 smear outline

- README.hbs
- README.md
> add docs for css font loading api

- include/canvas-2d-shape-renderer.js
- include/canvas-2d-text-renderer.js
- include/global-constants.js
- include/subtitle-parser.js
- include/util.js
- sbin/commands/local-debug.sh
- src/canvas-2d-shape-renderer.js
- src/canvas-2d-text-renderer.js
- src/global-constants.js
- src/renderer-main.js
- src/shader.js
- src/shaders/positioning.vertex.glsl
- src/style-override.js
- src/subtitle-parser.js
- src/util.js
Added word wrap & started to get ready for a serialization API.
Fixed a bunch of bugs as well.
> Preparation for serialization API & addition of word wrap.

- sbin/bootstrap.sh
- sbin/commands/local-compile.sh
- sbin/helpers/error_formatter.sh
- sbin/helpers/file-modification-test.sh
- src/canvas-2d-shape-renderer.js
- src/renderer-main.js
- src/shader.js
Got build scripts working on BSD and Darwin.
Some code cleanup/fixes.
> Code Cleanup & Build Script work for OSX/BSD

- Makefile
- package.json
- sbin/commands/npm-package.sh
- src/include.js
fixes include.js to support CDNs and other remote hosts correctly.
> Fixes for include.js for unpkg CDN.

- src/sabre.js
- src/shaders/positioning.fragment.glsl
Update to shaders to fix alpha values not applying correctly.
> Fix fades not working.

- package.json
- src/canvas-2d-shape-renderer.js
- src/canvas-2d-text-renderer.js
- src/shaders/positioning.fragment.glsl
Added front-end tag to npm package as well
> Fixes for color artifacting in blends.

- src/renderer-main.js
Fixed a bug that resulted in the output of checkReadyToRender being inverted.
> Fix for bug inverting checkReadyToRender.

- src/canvas-2d-shape-renderer.js
- src/sabre.js
- src/shaders/gauss_blur.1.fragment.glsl
- src/shaders/gauss_blur.2.fragment.glsl
Cuts off gaussian blur after 3 std deviations.
> Gaussian Blur optimization

- README.hbs
- README.md
- src/canvas-2d-shape-renderer.js
- src/renderer-main.js
- src/sabre.js
- src/subtitle-parser.js
Fixed a race condition in the loading system.
> Fixed a loading race condition, Documentation updates.

- README.hbs
- README.md
- src/renderer-main.js
- src/sabre.js
- src/scheduler.js
- src/style-override.js
- src/subtitle-parser.js
Fixing a race condition in loading system.
Clarified some documentation.
> Fix Race Condition in Loading System Part 2

- README.hbs
- README.md
- include/canvas-2d-text-renderer.js
- package.json
- src/canvas-2d-shape-renderer.js
- src/canvas-2d-text-renderer.js
- src/renderer-main.js
- src/shaders/positioning.fragment.glsl
- src/shaders/positioning.vertex.glsl
- src/subtitle-parser.js
This PR fixes inverted alpha values in alpha overrides. It also gets Emoji and Colored Fonts working.
> Fixes for emoji and colored fonts. Fixed error in parsing alpha overrides.

- sbin/commands/pre-commit.sh
- src/__tests__/color.test.js
- src/__tests__/style-override.test.js
- src/__tests__/subtitle-event.test.js
- src/__tests__/test-constants/style-override.constants.js
- src/__tests__/test-utils/style-override.uils.js
- src/canvas-2d-text-renderer.js
- src/renderer-main.js
- src/subtitle-parser.js
> Various bugfixes including fixing commits to require passing all tests.

- README.hbs
- README.md
- include/shared.include.js
- include/util.js
Cleanup some oversights and update readme.
> Includes cleanup & Readme Updates

- README.hbs
- README.md
Fix some formatting in the README.
> Update Readme to fix some formatting issues.

- README.hbs
- README.md
- package.json
- sbin/commands/npm-package.sh
- types/sabre.d.ts
Added types/bindings for TypeScript. Update README.md to include openbase link.
> Add TypeScript Types, update readme.

- package.json
- sbin/commands/npm-package.sh
Fixed an issue with packaging the types.
> Fix error in type packaging.

- include/canvas-2d-shape-renderer.js
- include/canvas-2d-text-renderer.js
- include/lib/earcut.js
- src/canvas-2d-shape-renderer.js
- src/canvas-2d-text-renderer.js
- src/lib/earcut.js
- src/renderer-main.js
- src/shaders/clip.fragment.glsl
- src/shaders/clip.vertex.glsl
- src/shaders/positioning.fragment.glsl
- src/subtitle-parser.js
This PR also fixes subtitle viewport scaling.
> Implement \clip and \iclip.

- src/canvas-2d-shape-renderer.js
- src/canvas-2d-text-renderer.js
There were some things being done out of order and other issues.
> Fixes to 2d rendering of subtitles and shapes.

- include/lib/BSpline.js
- include/lib/earcut.js
- include/sabre.js
- include/util.js
- sbin/commands/local-debug.sh
- sbin/defines/closure-defines.sh
- src/canvas-2d-shape-renderer.js
- src/canvas-2d-text-renderer.js
- src/lib/earcut.js
- src/renderer-main.js
- src/sabre.js
- src/scheduler.js
- src/shaders/clip.vertex.glsl
- src/shaders/gauss_blur.1.fragment.glsl
- src/shaders/gauss_blur.2.fragment.glsl
- src/shaders/positioning.vertex.glsl
- src/subtitle-parser.js
- src/util.js
> Fixes for rotation and some typing fixes.

- README.hbs
- README.md
Switch to using jsdelivr as primary CDN.
> Update docs to recommend jsdelivr.

- include/shared.include.js
- sbin/defines/closure-defines.sh
- sbin/defines/tools-defines.sh
- src/canvas-2d-shape-renderer.js
- src/canvas-2d-text-renderer.js
- src/renderer-main.js
- src/sabre.js
- src/scheduler.js
- src/shader.js
- src/style-override.js
- src/style.js
- src/subtitle-event.js
- src/subtitle-parser.js
- src/util.js
Get library working with bundlers.
> Fixes to get library working with webpack.

- .eslintrc.json
Also fixed require being undefined.
> Disable some ESLint checks that aren't needed.

- package.json
- src/canvas-2d-shape-renderer.js
- src/canvas-2d-text-renderer.js
- src/renderer-main.js
- src/sabre.js
- src/scheduler.js
- src/style-override.js
- src/style.js
- src/subtitle-event.js
- src/subtitle-parser.js
Add @types/offscreencanvas as a dependency to make it easier for people to use this library via typescript.
> Add NPM Package Dependancy for typescript.

- src/canvas-2d-text-renderer.js
- src/sabre.js
- src/shader.js
This "fixes" older browsers including non-chromium edge.
"fixes" here means gets the subtitles displaying, however crucial font information is missing so it may not display correctly.
> Fixes for older browsers inc. non-chromium edge.

- src/canvas-2d-shape-renderer.js
- src/canvas-2d-text-renderer.js
- src/renderer-main.js
- src/sabre.js
- src/scheduler.js
- src/style-override.js
- src/style.js
- src/subtitle-event.js
- src/subtitle-parser.js
- src/util.js
Fix the tests to work with the loading system fixes.
> Fixes for tests.

- src/canvas-2d-shape-renderer.js
- src/renderer-main.js
- src/subtitle-parser.js
Fixed shape bounds function.
Fixed an error in SSA style parsing.
Fixed sign on shear transformations.
> Fixes for several bugs including shape bounds, SSA style parsing, and shear transformations.

- src/canvas-2d-text-renderer.js
- src/shaders/positioning.fragment.glsl
Simplified some conditions, removed some unneeded code.
> Small fixes to the code.

- src/canvas-2d-text-renderer.js
Revert bad antialiasing fix, the issue will have to be fixed as part of the refactor to render characters individually.
> Revert bad antialiasing fix.

- jest.config.js
- sbin/defines/tools-defines.sh
Fix the test system to work with changes to Jest.
> Fixes for new test system updates.

- src/__tests__/parser.test.js
- src/__tests__/testfiles/test1.ass
- src/__tests__/testfiles/test2.ass
- src/subtitle-parser.js
Fixed bugs found in the process.
> Added initial tests for subtitle parser.

- src/renderer-main.js
Fixed an error in recent commits that caused the shear in the Y axis to be incorrect.
> Fix shear matrix to be correct.

- src/__tests__/parser.test.js
- src/__tests__/testfiles/test1.ass
- src/__tests__/testfiles/test1.ssa
- src/__tests__/testfiles/test2.ass
- src/__tests__/testfiles/test2.ssa
- src/subtitle-parser.js
Added tests for substation alpha.
Fixed bugs encountered along the way.
> Added tests for substation alpha.

- include/canvas-2d-shape-renderer.js
- include/canvas-2d-text-renderer.js
- src/canvas-2d-shape-renderer.js
- src/canvas-2d-text-renderer.js
- src/renderer-main.js
This resolves a bug with blurs and gets us ready to implement #72 caching characters on the GPU.
> Switch to laying out glyphs individually.

- src/renderer-main.js
Fixed a small performance bug and a variable declaration.
> Small fixes to the rendering code.

- include/shared.include.js
- src/subtitle-parser.js
- src/util.js
Various small fixes for a few bugs and some gramatical and code style issues.
> Gramatical, code style & includes fixes.

- src/canvas-2d-shape-renderer.js
- src/renderer-main.js
> Fixed up code style related to parseFloat.

- include/canvas-2d-text-renderer.js
- include/util.js
- src/canvas-2d-shape-renderer.js
- src/canvas-2d-text-renderer.js
- src/renderer-main.js
- src/shaders/cache.fragment.glsl
- src/shaders/cache.vertex.glsl
- src/shaders/positioning.fragment.glsl
- src/subtitle-tags.js
- src/util.js
This pull request implements character caching for text characters and also fixes a bug for Safari 16.
> Character caching

- Makefile
- README.md
- include/shared.include.js
- scripts/commands/generate-readme.sh
- scripts/defines/tools-defines.sh
- src/canvas-2d-shape-renderer.js
- src/canvas-2d-text-renderer.js
- src/renderer-main.js
- src/subtitle-parser.js
- src/util.js
Correctly implemented HIDPI support, fixed documentation on viewport pixel type.
> Clarified viewport pixel type and implemented HIDPI support.

- src/renderer-main.js
Made the cache framebuffer dependent solely on the canvas and screen size.
> Made cache framebuffer size more reasonable.

- src/canvas-2d-shape-renderer.js
- src/canvas-2d-text-renderer.js
- src/color.js
- src/font-server.js
- src/lib/BSpline.js
- src/lib/earcut.js
- src/sabre.js
- src/shader.js
- src/style-override.js
- src/style.js
- src/subtitle-event.js
- src/subtitle-parser.js
- src/util.js
Had to delete the pull, botched the ammend 
- (Same fixes as before) Nothing changed other than the described indent at sabre.js fixed
Redo of #95. Closes #92.
> Added function names for debuggers.

- README.hbs
- README.md
- include/canvas-2d-text-renderer.js
- src/renderer-main.js
Fixed various documentation oversights in addition to fixing skewing for subtitles.
> Fixup skewing for subtitles.

- src/canvas-2d-shape-renderer.js
- src/canvas-2d-text-renderer.js
- Stopped the renderers from drawing outlines if there were wasn't one.
- Fixed the Karaoke wipe to work correctly.
- Fixed a typo in the text renderer.
> Fixed up various things in the 2D renderers.

- include/shared.include.js
- src/font-server.js
- Fixed a bug with incorrect name fetching for unicode.
- Added selecting based on preferredFamily and preferredSubfamily.
> Fixes to font server for better font selection.

- README.hbs
- README.md
- Updated code snippet examples
- Updated getting started verbiage
> Updated documentation examples

- README.hbs
- README.md
- src/global-constants.js
- src/sabre.js
- src/subtitle-parser.js
Also fixed various documentation comments.
> Updates to documentation.

- scripts/bootstrap.sh
- scripts/commands/local-compile.sh
- scripts/commands/local-debug.sh
- scripts/commands/npm-package.sh
- scripts/commands/pre-commit.sh
- scripts/commands/test.sh
- scripts/helpers/error_formatter.sh
- scripts/helpers/execute-java.sh
- scripts/helpers/execute-node.sh
- scripts/helpers/execute-toolscript.sh
- scripts/helpers/file-modification-test.sh
Fixed macOS and BSD compatibility of build system some.
> Build system fix for BSD and Darwin

- scripts/defines/tools-defines.sh
Updated the closure compiler version that the build script uses.
> Update closure compiler version.

- types/sabre.d.ts
> Update Typescript types with new API changes.

- src/renderer-main.js
- src/shaders/gauss_blur.1.fragment.glsl
- src/shaders/gauss_blur.2.fragment.glsl
The ImageBitmap transfer mode would only output one good frame per time the subtitles update, this has been fixed.
Some Gaussian Blur fixes are also included in this PR.
> Fixed ImageBitmap transfer mode for both getFrame and drawFrame

- CONTRIBUTING.md
- README.hbs
- README.md
- include/canvas-2d-shape-renderer.js
- include/canvas-2d-text-renderer.js
- include/color.js
- include/font-server.js
- include/global-constants.js
- include/renderer-main.js
- include/scheduler.js
- include/shader.js
- include/shared.include.js
- include/style-override.js
- include/style.js
- include/subtitle-event.js
- include/subtitle-parser.js
- include/subtitle-tags.js
- include/text-server.js
- src/canvas-2d-shape-renderer.js
- src/canvas-2d-text-renderer.js
- src/font-server.js
- src/global-constants.js
- src/renderer-main.js
- src/scheduler.js
- src/shader.js
- src/subtitle-parser.js
- src/subtitle-tags.js
- src/text-server.js
- src/util.js
> Implemented Windows and DOS codepage decoding.

- scripts/commands/update-dependencies.sh
This fixes a incompatibility with the automated build environment.
> Fixup build script for automated build enviroment.

- jest.config.js
- scripts/commands/update-dependencies.sh
- src/lib/codepage.js
- src/renderer-main.js
Fixed jest scope to only look in src folder.
Fixed codepage library patches.
Added padding to glyph cache to fix vertical line artifacting.
> Fixes for Jest's scope, codepage, vertical line artifacting
